from mcp.server.fastmcp import FastMCP
import nest_asyncio
import json
from pathlib import Path

nest_asyncio.apply()

mcp = FastMCP("DocumentToPPT")


# ─────────────────────────────────────────────
# TOOL 1 — Read Document
# ─────────────────────────────────────────────
@mcp.tool()
def read_document(file_path: str) -> str:
    """
    Read content from a document file.
    Supported formats: .txt, .pdf, .docx
    """
    path = Path(file_path)
    if not path.exists():
        return f"Error: File not found at {file_path}"

    ext = path.suffix.lower()

    if ext == ".txt":
        return path.read_text(encoding="utf-8")

    elif ext == ".pdf":
        try:
            import pdfplumber
            with pdfplumber.open(file_path) as pdf:
                text = "\n".join(page.extract_text() or "" for page in pdf.pages)
            return text.strip()
        except ImportError:
            return "Error: pdfplumber not installed."

    elif ext in (".docx", ".doc"):
        try:
            from docx import Document
            doc = Document(file_path)
            return "\n".join(p.text for p in doc.paragraphs if p.text.strip())
        except ImportError:
            return "Error: python-docx not installed."

    return f"Error: Unsupported file type '{ext}'. Supported: .txt, .pdf, .docx"


# ─────────────────────────────────────────────
# TOOL 2 — Summarize & Structure with OpenAI
# ─────────────────────────────────────────────
@mcp.tool()
def summarize_content(text: str, api_key: str, slide_count: int = 6) -> str:
    """
    Use OpenAI to narrow down document content and structure it
    as a JSON outline for a PowerPoint presentation.
    Returns JSON with title and slide bullets.
    """
    try:
        from openai import OpenAI
        client = OpenAI(api_key=api_key)

        prompt = f"""Analyze this document and extract the most important information for a {slide_count}-slide PowerPoint.
Return ONLY valid JSON — no markdown, no explanation — in this exact format:
{{
  "title": "Presentation Title",
  "subtitle": "A short subtitle or author name",
  "slides": [
    {{
      "title": "Slide Title",
      "bullets": ["Key point 1", "Key point 2", "Key point 3"]
    }}
  ]
}}

Document:
{text[:8000]}"""

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
        )
        raw = response.choices[0].message.content.strip()

        # Strip markdown code fences if present
        if "```json" in raw:
            raw = raw.split("```json")[1].split("```")[0].strip()
        elif "```" in raw:
            raw = raw.split("```")[1].split("```")[0].strip()

        # Validate JSON
        json.loads(raw)
        return raw

    except Exception as e:
        return f"Error summarizing: {str(e)}"


# ─────────────────────────────────────────────
# TOOL 3 — Create PowerPoint
# ─────────────────────────────────────────────
@mcp.tool()
def create_ppt(structured_content: str, output_path: str = "output.pptx") -> str:
    """
    Create a styled PowerPoint file from structured JSON content
    produced by summarize_content.
    """
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt, Emu
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN

        data = json.loads(structured_content)
        prs = Presentation()
        prs.slide_width = Inches(13.33)
        prs.slide_height = Inches(7.5)

        # ── Title slide ──────────────────────────────
        title_slide = prs.slides.add_slide(prs.slide_layouts[0])
        title_slide.shapes.title.text = data.get("title", "Presentation")
        subtitle_ph = title_slide.placeholders[1]
        subtitle_ph.text = data.get("subtitle", "Generated by AI")

        # Style title text
        for para in title_slide.shapes.title.text_frame.paragraphs:
            for run in para.runs:
                run.font.size = Pt(40)
                run.font.bold = True
                run.font.color.rgb = RGBColor(0x1F, 0x39, 0x7D)

        # ── Content slides ───────────────────────────
        for slide_data in data.get("slides", []):
            slide = prs.slides.add_slide(prs.slide_layouts[1])

            # Slide title
            slide.shapes.title.text = slide_data.get("title", "")
            for para in slide.shapes.title.text_frame.paragraphs:
                for run in para.runs:
                    run.font.size = Pt(28)
                    run.font.bold = True
                    run.font.color.rgb = RGBColor(0x1F, 0x39, 0x7D)

            # Bullet points
            tf = slide.placeholders[1].text_frame
            tf.clear()
            for i, bullet in enumerate(slide_data.get("bullets", [])):
                if i == 0:
                    p = tf.paragraphs[0]
                else:
                    p = tf.add_paragraph()
                p.text = bullet
                p.level = 0
                for run in p.runs:
                    run.font.size = Pt(18)

        prs.save(output_path)
        slides_count = len(data.get("slides", []))
        return f"PPT created: {output_path}  ({slides_count} content slides + 1 title slide)"

    except json.JSONDecodeError as e:
        return f"Error: Invalid JSON content — {str(e)}"
    except Exception as e:
        return f"Error creating PPT: {str(e)}"


# ─────────────────────────────────────────────
# TOOL 4 — Full Pipeline (orchestrator)
# ─────────────────────────────────────────────
@mcp.tool()
def document_to_ppt(
    file_path: str,
    api_key: str,
    output_path: str = "output.pptx",
    slide_count: int = 6,
) -> str:
    """
    Full pipeline:
      1. Read the document (txt / pdf / docx)
      2. Summarize and structure content with OpenAI
      3. Generate a styled PowerPoint file

    Args:
        file_path:   Path to the input document
        api_key:     OpenAI API key
        output_path: Where to save the .pptx file (default: output.pptx)
        slide_count: Number of content slides to generate (default: 6)
    """
    print(f"\n[1/3] Reading document: {file_path}")
    text = read_document(file_path)
    if text.startswith("Error:"):
        return text

    print(f"[2/3] Summarizing {len(text):,} characters with OpenAI gpt-4o-mini ...")
    structured = summarize_content(text, api_key, slide_count)
    if structured.startswith("Error"):
        return structured

    print(f"[3/3] Creating PowerPoint → {output_path}")
    result = create_ppt(structured, output_path)
    return result


# ─────────────────────────────────────────────
# MCP Flow HTML builder
# ─────────────────────────────────────────────
TOOLS = [
    ("read_document",    "📄 read_document",    "Reads .txt / .pdf / .docx"),
    ("summarize_content","🤖 summarize_content","Calls OpenAI to structure slides"),
    ("create_ppt",       "📊 create_ppt",       "Builds the PowerPoint file"),
]

STATUS_COLORS = {
    "waiting": ("#e2e8f0", "#64748b", "○"),
    "active":  ("#fef9c3", "#b45309", "⟳"),
    "done":    ("#dcfce7", "#15803d", "✓"),
    "error":   ("#fee2e2", "#b91c1c", "✗"),
}

def make_flow_html(states: dict, details: dict) -> str:
    cards = []
    for key, label, desc in TOOLS:
        st = states.get(key, "waiting")
        bg, fg, icon = STATUS_COLORS[st]
        detail_html = ""
        if details.get(key):
            detail_html = f'<div style="margin-top:8px;font-size:12px;color:#374151;background:#f9fafb;border-radius:6px;padding:8px;max-height:80px;overflow-y:auto;word-break:break-word;">{details[key]}</div>'
        cards.append(f"""
        <div style="flex:1;border-radius:12px;border:2px solid {fg};background:{bg};padding:16px;min-width:180px;">
          <div style="font-size:20px;font-weight:700;color:{fg};">{icon} {label}</div>
          <div style="font-size:12px;color:#6b7280;margin-top:4px;">{desc}</div>
          {detail_html}
        </div>""")

    arrows = '<div style="font-size:28px;color:#94a3b8;align-self:center;padding:0 4px;">→</div>'
    row = arrows.join(cards)

    return f"""
    <div style="font-family:sans-serif;padding:12px;">
      <div style="font-size:16px;font-weight:700;color:#1e3a5f;margin-bottom:12px;">
        🔄 MCP Tool Flow
      </div>
      <div style="display:flex;gap:4px;align-items:stretch;flex-wrap:wrap;">
        {row}
      </div>
      <div style="margin-top:12px;font-size:12px;color:#9ca3af;">
        ○ waiting &nbsp;|&nbsp; ⟳ active &nbsp;|&nbsp; ✓ done &nbsp;|&nbsp; ✗ error
      </div>
    </div>"""


# ─────────────────────────────────────────────
# Gradio generator (streams MCP flow updates)
# ─────────────────────────────────────────────
import gradio as gr

def run_ui(file, api_key, output_name, slide_count):
    states  = {k: "waiting" for k, *_ in TOOLS}
    details = {}
    log     = []

    def emit(extra_log=None, file_out=None):
        if extra_log:
            log.append(extra_log)
        return make_flow_html(states, details), "\n".join(log), file_out

    if file is None:
        yield emit("❌ Please upload a document.")
        return
    if not api_key.strip():
        yield emit("❌ Please enter your OpenAI API key.")
        return

    out_path = (output_name.strip() or "output.pptx")
    if not out_path.endswith(".pptx"):
        out_path += ".pptx"

    # ── Tool 1: read_document ────────────────
    states["read_document"] = "active"
    details["read_document"] = f"file: {file.name}"
    yield emit("📄 [read_document] Reading document...")

    text = read_document(file.name)
    if text.startswith("Error:"):
        states["read_document"] = "error"
        details["read_document"] = text
        yield emit(f"❌ {text}")
        return

    states["read_document"] = "done"
    details["read_document"] = f"✓ {len(text):,} characters extracted"
    yield emit(f"✅ [read_document] {len(text):,} characters read.")

    # ── Tool 2: summarize_content ────────────
    states["summarize_content"] = "active"
    details["summarize_content"] = f"model: gpt-4o-mini | slides: {int(slide_count)}"
    yield emit("🤖 [summarize_content] Calling OpenAI to structure content...")

    structured = summarize_content(text, api_key.strip(), int(slide_count))
    if structured.startswith("Error"):
        states["summarize_content"] = "error"
        details["summarize_content"] = structured
        yield emit(f"❌ {structured}")
        return

    try:
        slide_titles = [s["title"] for s in json.loads(structured).get("slides", [])]
        states["summarize_content"] = "done"
        details["summarize_content"] = "Slides: " + " | ".join(slide_titles[:4]) + ("..." if len(slide_titles) > 4 else "")
    except Exception:
        states["summarize_content"] = "done"
        details["summarize_content"] = "✓ Structured JSON received"
    yield emit(f"✅ [summarize_content] {len(slide_titles)} slides structured.")

    # ── Tool 3: create_ppt ───────────────────
    states["create_ppt"] = "active"
    details["create_ppt"] = f"output: {out_path}"
    yield emit(f"📊 [create_ppt] Building PowerPoint → {out_path}...")

    result = create_ppt(structured, out_path)
    if result.startswith("Error"):
        states["create_ppt"] = "error"
        details["create_ppt"] = result
        yield emit(f"❌ {result}")
        return

    states["create_ppt"] = "done"
    details["create_ppt"] = f"✓ {result}"
    yield emit(f"✅ [create_ppt] {result}", out_path)


# ─────────────────────────────────────────────
# Gradio UI
# ─────────────────────────────────────────────
with gr.Blocks(title="Document → PPT (MCP)", css=".gr-button{font-size:15px}") as app:
    gr.Markdown("# 📊 Document → PowerPoint via MCP\nUpload a document and watch the MCP tools execute step by step.")

    with gr.Row():
        # ── Left: Inputs ─────────────────────
        with gr.Column(scale=1):
            gr.Markdown("### ⚙️ Inputs")
            file_input    = gr.File(label="Document (.txt / .pdf / .docx)", file_types=[".txt", ".pdf", ".docx"])
            api_key_input = gr.Textbox(label="OpenAI API Key", placeholder="sk-...", type="password")
            with gr.Row():
                output_name = gr.Textbox(label="Output filename", value="output.pptx", scale=3)
                slide_count = gr.Slider(label="Slides", minimum=3, maximum=15, value=6, step=1, scale=2)
            run_btn = gr.Button("🚀 Generate PPT", variant="primary", size="lg")

        # ── Right: MCP flow + log ─────────────
        with gr.Column(scale=2):
            flow_panel  = gr.HTML(value=make_flow_html(
                {k: "waiting" for k, *_ in TOOLS}, {}))
            log_box     = gr.Textbox(label="Execution Log", lines=6, interactive=False)
            download_btn = gr.File(label="⬇️ Download PPT")

    run_btn.click(
        fn=run_ui,
        inputs=[file_input, api_key_input, output_name, slide_count],
        outputs=[flow_panel, log_box, download_btn]
    )


# ─────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────
if __name__ == "__main__":
    app.launch()
